### ISSUE TITLE
Flycast sometimes crashes while using fast forward with Vulkan if "Duplicate frames" is enabled

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#1138]
Platform / OS / Hardware: Windows 10 / i5-12400F / RTX 3060 Ti

Github hash: 278f26aadddd5811c5879be79fb424e55a67e166

Hardware: DC / Naomi / Naomi 2 / Sammy / System SP

**_Description of the Issue_**

While using Vulkan with "Duplicate frames" there's a high chance for Flycast to crash when using fast forward.

Here's the minidump + the .log that was next to it: [fc_crash.zip](https://github.com/flyinghead/flycast/files/11990478/fc_crash.zip)

**_Debugging Steps Tested_**

  * Select Vulkan renderer.
  * Enable "Duplicate frames".
  * Start a game, press fast forward hotkey to trigger the crash (might require multiple attempts).

**_Logs Gathered_**

```
00:00:000 sdl/sdl.cpp:601 N[RENDERER]: Monitor refresh rate: 120 Hz (1920 x 1080)
00:00:027 rend/vulkan/vulkan_context.cpp:250 N[RENDERER]: Vulkan API 1.1. Device NVIDIA GeForce RTX 3060 Ti
00:00:027 rend/vulkan/vulkan_context.cpp:258 N[RENDERER]: eR5G5B5A1UnormPack16 not supported for optimal tiling
00:00:027 rend/vulkan/vulkan_context.cpp:272 N[RENDERER]: eR4G4B4A4UnormPack16 not supported for optimal tiling
00:00:105 rend/vulkan/vulkan_context.h:268 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:106 rend/gui.cpp:297 N[RENDERER]: Screen DPI is 96, size 1148 x 728. Scaling by 1.00
00:00:239 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
00:00:243 oslib/oslib.cpp:210 N[COMMON]: Uploading minidump C:\Users\B-S\AppData\Local\Temp\\fb09e9d0-46cb-43ad-a00b-e08d636147d0.dmp
00:05:908 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:05:915 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 00007ff46f3b0000 RAM(16 MB) 00007ff47b3b0000 VRAM64(8 MB) 00007ff4733b0000 ARAM(2 MB) 00007ff48f3b0000
00:05:918 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:05:925 hw/mem/addrspace.cpp:462 N[VMEM]: BASE 00007ff46f3b0000 RAM(16 MB) 00007ff47b3b0000 VRAM64(8 MB) 00007ff4733b0000 ARAM(2 MB) 00007ff48f3b0000
00:05:935 emulator.cpp:54 N[BOOT]: Game ID is [MK-51002]
00:05:936 emulator.cpp:54 N[BOOT]: Game ID is [MK-51002]
00:09:150 rend/vulkan/vulkan_context.h:268 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:09:155 windows/fault_handler.cpp:106 E[COMMON]: [GPF] PC 00007ffd20a73a14 unhandled access to 0000000000000000
```

**Comment by bslenul** [comment]
Got this with gdb, no idea if it helps:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffce12b3aab in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
(gdb) bt
#0  0x00007ffce12b3aab in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
#1  0x00007ffce1301553 in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
#2  0x00007ffce11f6402 in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
#3  0x00007ff734a63fe8 in vk::Queue::submit<vk::DispatchLoaderDynamic> (d=..., fence=..., submits=..., this=0x7ff736c99108 <theVulkanContext+264>) at G:/msys64/home/B-S/flycast/core/deps/Vulkan-Headers/include/vulkan/vulkan_handles.hpp:2615
#4  VulkanContext::EndFrame (this=this@entry=0x7ff736c99000 <theVulkanContext>, overlayCmdBuffer=..., overlayCmdBuffer@entry=...) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_context.cpp:848
#5  0x00007ff734a6a46b in VulkanContext::PresentFrame (this=0x7ff736c99000 <theVulkanContext>, image=..., imageView=..., extent=..., aspectRatio=1.33333349) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_context.cpp:969
#6  0x00007ff734e3cae3 in ScreenDrawer::PresentFrame (this=0xe239f8) at G:/msys64/home/B-S/flycast/core/rend/vulkan/drawer.h:286
#7  ScreenDrawer::PresentFrame (this=0xe239f8) at G:/msys64/home/B-S/flycast/core/rend/vulkan/drawer.h:281
#8  VulkanRenderer::Present (this=0xe23570) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_renderer.cpp:89
#9  VulkanRenderer::Present (this=0xe23570) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_renderer.cpp:84
#10 0x00007ff73495b122 in PvrMessageQueue::present (this=<optimized out>) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:230
#11 PvrMessageQueue::execute (this=0x7ff7364cc660 <pvrQueue>, msg=...) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:160
#12 PvrMessageQueue::waitAndExecute (timeoutMs=<optimized out>, this=<optimized out>) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:101
#13 rend_single_frame (enabled=enabled@entry=@0x5fefef: true) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:255
#14 0x00007ff734835be7 in Emulator::render (this=0x7ff73542a040 <emu>) at G:/msys64/home/B-S/flycast/core/emulator.cpp:986
#15 0x00007ff734a1363b in mainui_rend_frame () at G:/msys64/home/B-S/flycast/core/rend/mainui.cpp:59
#16 0x00007ff734a1395a in mainui_loop () at G:/msys64/home/B-S/flycast/core/rend/mainui.cpp:96
#17 0x00007ff734a9ce8e in SDL_main (argc=<optimized out>, argv=<optimized out>) at G:/msys64/home/B-S/flycast/core/windows/winmain.cpp:930
#18 0x00007ff734b132de in main_getcmdline ()
#19 0x00007ff7348312ee in __tmainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:267
#20 0x00007ff7348313e6 in WinMainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:157
```
^ that's with RelWithDebInfo, it is a bit different with Debug:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffce12b3aab in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
(gdb) bt
#0  0x00007ffce12b3aab in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
#1  0x00007ffce1301553 in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
#2  0x00007ffce11f6402 in vkGetInstanceProcAddr () from C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_675be35f1ba2315e\nvoglv64.dll
#3  0x00007ff696ef52d3 in vk::Queue::submit<vk::DispatchLoaderDynamic> (d=..., fence=..., submits=..., this=0x7ff69947b1e8 <theVulkanContext+264>) at G:/msys64/home/B-S/flycast/core/deps/Vulkan-Headers/include/vulkan/vulkan_funcs.hpp:777
#4  VulkanContext::EndFrame (this=0x7ff69947b0e0 <theVulkanContext>, overlayCmdBuffer=...) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_context.cpp:848
#5  0x00007ff696ef65e0 in VulkanContext::PresentFrame (this=0x7ff69947b0e0 <theVulkanContext>, image=..., imageView=..., extent=..., aspectRatio=1.33333349) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_context.cpp:969
#6  0x00007ff6972b7a1a in ScreenDrawer::PresentFrame (this=0x262ba38) at G:/msys64/home/B-S/flycast/core/rend/vulkan/drawer.h:286
#7  0x00007ff6972d58c1 in VulkanRenderer::Present (this=0x262b5b0) at G:/msys64/home/B-S/flycast/core/rend/vulkan/vulkan_renderer.cpp:89
#8  0x00007ff6972e5d19 in PvrMessageQueue::present (this=0x7ff698cae720 <pvrQueue>) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:230
#9  0x00007ff6972e5ccf in PvrMessageQueue::execute (this=0x7ff698cae720 <pvrQueue>, msg=...) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:160
#10 0x00007ff6972e56bb in PvrMessageQueue::waitAndExecute (this=0x7ff698cae720 <pvrQueue>, timeoutMs=50) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:101
#11 0x00007ff696dd79e6 in rend_single_frame (enabled=@0x5ff64f: true) at G:/msys64/home/B-S/flycast/core/hw/pvr/Renderer_if.cpp:255
#12 0x00007ff696c55154 in Emulator::render (this=0x7ff697c0c1c0 <emu>) at G:/msys64/home/B-S/flycast/core/emulator.cpp:986
#13 0x00007ff696e8a481 in mainui_rend_frame () at G:/msys64/home/B-S/flycast/core/rend/mainui.cpp:59
#14 0x00007ff696e8a6fc in mainui_loop () at G:/msys64/home/B-S/flycast/core/rend/mainui.cpp:96
#15 0x00007ff696f2b883 in SDL_main (argc=1, argv=0x1dc730) at G:/msys64/home/B-S/flycast/core/windows/winmain.cpp:930
#16 0x00007ff696f948fe in main_getcmdline ()
#17 0x00007ff696c512ee in __tmainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:267
#18 0x00007ff696c513e6 in WinMainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:157
```

**Comment by flyinghead** [comment]
I believe this problem has been mentioned before but I haven't been able to reproduce it. (I only have a 60 Hz monitor.)
It's crashing in the nvidia driver so no easy way to figure out what it doesn't like.

What could help would be to install the vulkan sdk (https://vulkan.lunarg.com/) and run flycast with validation layers enabled (vkconfig). If Flycast is doing something wrong with the vulkan API, it should be logged.

**Comment by bslenul** [comment]
OK, never used vkconfig before, I ran it, added Flycast and triggered the crash, is that all I have to do? If that the case then here's the log: [flycast.txt](https://github.com/flyinghead/flycast/files/12000074/flycast.txt)

**Comment by flyinghead** [comment]
This is great.
I assume the 3 errors happen at or just before the time of the crash, correct?

**Comment by bslenul** [comment]
Yes, the errors only appear on crash.

**Comment by flyinghead** [comment]
should be fixed in the latest master build

**Comment by bslenul** [comment]
Confirmed, thank you so much for the fix! ❤️ 

Closing!
