### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by android-1995** [flyinghead/flycast#206]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: android

Github hash: 5e619a70d416e3f0c70f450d7e6ad641516af3ea

Hardware: 

**_Description of the Issue_**

Sorry i'm a beginner

**_Debugging Steps Tested_**

  * git clone https://github.com/flyinghead/flycast.git
  * Android studio open flycast/shell/android-studio
  * run app

**_Logs Gathered_**

```
2021-03-15 16:22:55.105 6717-6717/com.flycast.emulator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flycast.emulator, PID: 6717
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.reicast.emulator.emu.JNIdc.<clinit>(JNIdc.java:10)
        at com.reicast.emulator.emu.JNIdc.getVirtualGamepadVibration(Native Method)
        at com.reicast.emulator.Emulator.getConfigurationPrefs(Emulator.java:41)
        at com.reicast.emulator.BaseGLActivity.onCreate(BaseGLActivity.java:80)
        at com.reicast.emulator.NativeGLActivity.onCreate(NativeGLActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3317)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3491)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2075)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7594)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

```

**Comment by flyinghead** [comment]
Quick and dirty way:
Comment out OpenMP in CMakeLists.txt
```
#find_package(OpenMP)
```

I don't have a better workaround for building with Android Studio. Upgrading to the latest version might help but no guarantee...

**Comment by android-1995** [comment]
thank you
