### ISSUE TITLE
Flycast crashes on exit

### ISSUE THREAD

**Issue by pjagiello** [flyinghead/flycast#763]
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Linux 64-bit, OpenGL
Github hash: b240da4
Hardware: 

CPU: Intel i5-4200M
GPU: Intel(R) HD Graphics 4600

**_Description of the Issue_**

This one is simple, exiting flycast (by closing the window) makes it crash. Don't need to even load the game first. (Just to make sure it's not somehow connected with #762 , this seems to happen regardless of audio device chosen).

**_Logs Gathered_**

```

$ flycast
00:00:197 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
00:00:232 rend/gui.cpp:262 N[RENDERER]: Screen DPI is 144, size 1232 x 806. Scaling by 1.08
00:00:341 rend/gles/gles.cpp:550 N[RENDERER]: OpenGL version 4.6
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Minidump saved to '/tmp/bef76420-2d92-47aa-3e7ffebd-375d1e21.dmp'

**Comment by cinnamonmatexfce** [comment]
This also happens you you remove (**MAKE A BACKUP FIRST!!**) all `.nvram` files?

**Comment by pjagiello** [comment]
I emptied my "data directory" (which is ~/.local/share/flycast), which contained a bunch of .nvmem files and it still crashes. (Or are these kept somewhere else?)

**Comment by cinnamonmatexfce** [comment]
> I emptied my "data directory" (which is ~/.local/share/flycast), which contained a bunch of .nvmem files and it still crashes. (Or are these kept somewhere else?)
> 
> 

Nope. `.local/share/flycast` is the right and only one for `data`.

**Comment by flyinghead** [comment]
@pjagiello Are you using the flatpak version or did you compile locally?

**Comment by pjagiello** [comment]
I compiled it locally.
Dump attached.
[53210fbf-c000-4104-4aaccaa3-d34bb99f.dmp.gz](https://github.com/flyinghead/flycast/files/9698727/53210fbf-c000-4104-4aaccaa3-d34bb99f.dmp.gz)

**Comment by flyinghead** [comment]
Thanks but I don't have the corresponding symbol file so it doesn't help much.

Ideally if you could debug flycast:
```
gdb flycast
run
```
then when it crashes:
```
backtrace
```

You need to have the symbols in the flycast executable for the backtrace to work.

**Comment by pjagiello** [comment]
Okay, so this was a minor rabbit hole - first of all, what I actually mean by "compiling locally" is installing [this AUR package](https://aur.archlinux.org/packages/flycast-git) (which I do acknowledge you do not maintain), and when attempting to do the same steps manually as the AUR package, I cannot reproduce the crash, so something about the package building process seems to be causing this... but nevertheless this is the stack trace I got:
```

Reading symbols from ./flycast...
(gdb) run
Starting program: /home/pj/Pobrane/flycast-git/src/build/flycast 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffee28be6c0 (LWP 53283)]
[New Thread 0x7ffee20bd6c0 (LWP 53284)]
[Thread 0x7ffee20bd6c0 (LWP 53284) exited]
00:00:480 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1920 x 1080)
[New Thread 0x7ffee20bd6c0 (LWP 53285)]
00:00:520 rend/gui.cpp:262 N[RENDERER]: Screen DPI is 144, size 822 x 791. Scaling by 1.08
[New Thread 0x7ffee12bc6c0 (LWP 53286)]
00:00:579 rend/gles/gles.cpp:550 N[RENDERER]: OpenGL version 4.6
[New Thread 0x7ffedbfff6c0 (LWP 53287)]
[Thread 0x7ffedbfff6c0 (LWP 53287) exited]
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Thread 1 "flycast" received signal SIGABRT, Aborted.
0x00007ffff75b949c in ?? () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff75b949c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7569958 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff755353d in abort () from /usr/lib/libc.so.6
#3  0x00007ffff78d2112 in std::__glibcxx_assert_fail (file=file@entry=0x555556954388 "/usr/include/c++/12.2.0/bits/stl_vector.h", line=line@entry=1123, 
    function=function@entry=0x555556971b68 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; reference = unsigned int&; size_type = long unsigne"..., condition=condition@entry=0x555556955963 "__n < this->size()") at /usr/src/debug/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x00005555566b4048 in std::vector<unsigned int, std::allocator<unsigned int> >::operator[] (this=0x7fffffffe4a0, __n=0) at /usr/include/c++/12.2.0/bits/stl_vector.h:1121
#5  std::vector<unsigned int, std::allocator<unsigned int> >::operator[] (__n=0, this=0x7fffffffe4a0) at /usr/include/c++/12.2.0/bits/stl_vector.h:1121
#6  OpenGLDriver::~OpenGLDriver (this=0x5555584cc190, __in_chrg=<optimized out>) at /home/pj/Pobrane/flycast-git/src/flycast/core/rend/gles/opengl_driver.cpp:71
#7  0x00005555566b408d in OpenGLDriver::~OpenGLDriver (this=0x5555584cc190, __in_chrg=<optimized out>) at /home/pj/Pobrane/flycast-git/src/flycast/core/rend/gles/opengl_driver.cpp:73
#8  0x000055555669c2c5 in std::default_delete<ImGuiDriver>::operator() (__ptr=<optimized out>, this=<optimized out>) at /usr/include/c++/12.2.0/bits/unique_ptr.h:95
#9  std::__uniq_ptr_impl<ImGuiDriver, std::default_delete<ImGuiDriver> >::reset (__p=0x0, this=<optimized out>) at /usr/include/c++/12.2.0/bits/unique_ptr.h:203
#10 std::unique_ptr<ImGuiDriver, std::default_delete<ImGuiDriver> >::reset (__p=0x0, this=<optimized out>) at /usr/include/c++/12.2.0/bits/unique_ptr.h:501
#11 GLGraphicsContext::preTerm (this=this@entry=0x555556b86de0 <theGLContext>) at /home/pj/Pobrane/flycast-git/src/flycast/core/wsi/gl_context.cpp:52
#12 0x000055555669c3de in SDLGLGraphicsContext::term (this=0x555556b86de0 <theGLContext>) at /home/pj/Pobrane/flycast-git/src/flycast/core/wsi/sdl.cpp:150
#13 0x000055555669c03a in termRenderApi () at /home/pj/Pobrane/flycast-git/src/flycast/core/wsi/switcher.cpp:83
#14 0x00005555555dfc42 in sdl_window_destroy () at /home/pj/Pobrane/flycast-git/src/flycast/core/sdl/sdl.cpp:662
#15 0x00005555555d8dd3 in main (argc=1, argv=0x7fffffffe8f8) at /home/pj/Pobrane/flycast-git/src/flycast/core/linux-dist/main.cpp:416

```

I haven't figured out yet why it doesn't seem to happen when running cmake and make manually instead of using `makepkg`, so I can't rule out that this isn't some issue with the AUR packaging, but maybe you'll find this helpful.

**Comment by flyinghead** [comment]
This is great. Thank you!

**Comment by flyinghead** [comment]
I just pushed a fix for this issue. Let me know if it works. Thanks!

**Comment by pjagiello** [comment]
I can confirm - on the newest master it doesn't crash anymore. Thanks for the fix!

**Comment by 71knight** [comment]
I would like to add, it crashes on exiting with retroarch also on Android 11.

**Comment by flyinghead** [comment]
@71knight This is very likely a different issue so please open a new issue for it
